fastcgipp:
  build: build/fastcgipp
  restart: always
  container_name: fastcgipp

  volumes:
    - ./src:/data

nginx:
  build: build/nginx
  restart: always
  container_name: fastcgipp-nginx

  links:
   - fastcgipp:fastcgipp

  ports:
   - "8068:80"

  volumes:
    - ./logs:/var/log/nginx
