fastcgipp:
  build: build
  restart: always
  container_name: fast-taggy-api

  ports:
    - "8068:80"

  volumes:
    - ./logs:/var/log/fastcgipp
    - ./logs:/var/log/nginx
    - ./html:/var/www/html
    - ./static:/var/www/static
    - ./src:/data
