fastcgi-daemon:
  build: build/fastcgi-daemon
  restart: always
  container_name: fastcgi-daemon

  environment:
   - CONF_FILE=fastcgi.conf

  volumes:
    - ./src:/data
    - ./tmp:/tmp/fastcgi

nginx:
  build: build/nginx
  restart: always
  container_name: fastcgi-nginx

  links:
   - fastcgi-daemon:fastcgi-daemon

  ports:
   - "8067:80"

  volumes:
    - ./logs:/var/log/nginx
    - ./tmp:/tmp/fastcgi
